---
# tasks file for swap
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ swapfile_dependencies }}"
  tags:
    - configuration
    - swapfile
    - swapfile-install
    - swapfile-install-dependencies

- name: write swap file
  command: fallocate -l {{ swapfile_size }} {{ swapfile_file }}
  args:
    creates: "{{ swapfile_file }}"
  register: write_swapfile
  when: swapfile_size != false
  tags:
    - configuration
    - swapfile
    - swapfile-write-file

- name: set swap file permissions
  file:
    path: "{{ swapfile_file }}"
    owner: root
    group: root
    mode: 0600
  when: swapfile_size != false
  tags:
    - configuration
    - swapfile
    - swapfile-set-file-permissions

- name: create swap file
  command: mkswap {{ swapfile_file }}
  register: create_swapfile
  when: swapfile_size != false and write_swapfile.changed
  tags:
    - configuration
    - swapfile
    - swapfile-mkswap

- name: enable swapfile
  command: swapon {{ swapfile_file }}
  when: swapfile_size != false and create_swapfile.changed
  tags:
    - configuration
    - swapfile
    - swapfile-enable-swapfile

- name: add swapfile to /etc/fstab
  mount:
    name: none
    src: "{{ swapfile_file }}"
    fstype: swap
    opts: sw
    passno: '0'
    dump: '0'
    state: present
  tags:
    - configuration
    - swapfile
    - swapfile-fstab

- name: configure vm.swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swapfile_swappiness }}"
    reload: true
    state: present
  when: swapfile_swappiness != false
  tags:
    - configuration
    - swapfile
    - swapfile-vm-swappiness

- name: configure vm.vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swapfile_vfs_cache_pressure }}"
    reload: true
    state: present
  when: swapfile_vfs_cache_pressure != false
  tags:
    - configuration
    - swapfile
    - swapfile-vm-vfs-cache-pressure
